# src/rl/video_wrapper.py
import gym
import numpy as np

class VideoWrapper(gym.Wrapper):
    """Wraps a Gym environment to record frames for training videos."""
    
    def __init__(self, env, recorder=None):
        super().__init__(env)  # important: gym.Wrapper will do type checks
        self.recorder = recorder
        self._enable_primitive_video_frames()

    def _enable_primitive_video_frames(self):
        """Turn on primitive-step capture when this wrapper is recording videos."""
        if self.recorder is None:
            return
        self.env.enable_primitive_video_frames()

    def reset(self, **kwargs):
        """Reset the env and capture the first frame of the next training episode."""
        obs = super().reset(**kwargs)
        if self.recorder:
            self.recorder.reset()
            frame = self.render(mode="rgb_array")
            self.recorder.capture(frame)
        return obs

    def step(self, action):
        """Capture every primitive-step frame generated by one recorded macro action."""
        obs, reward, done, info = super().step(action)
        if self.recorder:
            self._capture_recorded_macro_frames()
            if done:
                self.recorder.save(tag="train_episode")
        return obs, reward, done, info

    def _capture_recorded_macro_frames(self):
        """Save planner-style primitive frames, or one fallback macro frame if needed."""
        macro_frames = self.env.consume_primitive_video_frames()
        if not macro_frames:
            macro_frames = [self.render(mode="rgb_array")]
        for frame in macro_frames:
            self.recorder.capture(self._normalized_frame(frame))

    def _normalized_frame(self, frame):
        """Convert one render into a standard three-channel frame for video writing."""
        frame = np.array(frame)
        if frame.ndim == 2:
            return np.stack([frame] * 3, axis=-1)
        if frame.shape[2] == 4:
            return frame[:, :, :3]
        return frame

    def render(self, *args, **kwargs):
        """Delegate rendering to the wrapped Sokoban environment."""
        return self.env.render(*args, **kwargs)

    def close(self):
        """Close the wrapped env and any resources it owns."""
        return self.env.close()
    
    def seed(self, seed=None):
        """Forward seeding so training runs stay deterministic when requested."""
        return self.env.seed(seed)
